stages:
  - build
  - test
  - review
  - deploy

include:
  - project: 'taku-miyanaga/templates'
    ref: main
    file: 'OpenAI-Review.gitlab-ci.yml'

variables:
  CODE_REVIEW_DISABLED: '1'
  DOC_REVIEW_DISABLED: '0'

build:
  stage: build
  image: node:lts
  before_script:
    - npm i next react react-dom nextra nextra-theme-docs
  script:
    - npm run build # build to public path
    - npm run export
    - mv out public
  cache:
    key: "${CI_COMMIT_BRANCH}-build-artifact"
    paths:
      - public
    policy: push

markdown-lint:
  stage: test
  needs: [] # don't wait for build jobs
  variables:
    MARKDOWNLINT_VERSION: 0.23.0-alpine
  image:
    name: 06kellyjac/markdownlint-cli:${MARKDOWNLINT_VERSION}
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - markdownlint --version
  script:
    - find ./pages -name "*.mdx" -type f -print0 | xargs -0 markdownlint --config ./rules.json
  allow_failure: true

text-lint:
  image: node:16
  stage: test
  needs: [] # don't wait for build jobs
  before_script:
    - npm install textlint -g
    - npm install textlint-rule-preset-ja-spacing -g
    - npm install textlint-rule-preset-ja-technical-writing -g
    - npm install textlint-rule-spellcheck-tech-word -g
    - npm install textlint-filter-rule-allowlist -g
    - npm install textlint-filter-rule-comments -g
    - npm install textlint-rule-prh -g
    - npm list -g --depth=0
  script:
    - textlint ./pages

markdown-link-check:
  image: node:bookworm-slim
  stage: test
  needs: [] # don't wait for build jobs
  before_script:
    - apt update
    - apt install -y nkf
    - npm install markdown-link-check -g
  script:
    - cd ./sh
    - bash mlc.sh
  allow_failure: true

openai-doc-review:
  stage: review

openai-code-review:
  stage: review

pages: # this job only make the artifact for auto deployment
  stage: deploy
  dependencies:
    - build
  script:
    - cp -r assets public/assets
    - cp -r pdf public/pdf
  cache:
    key: "${CI_COMMIT_BRANCH}-build-artifact"
    paths:
      - public
    policy: pull
  artifacts:
    name: "html"
    paths:
      - public
    expire_in: 1 min # this aritifact will be deleted immediately to save disk space
  environment:
    name: production
    url: $CI_PAGES_URL
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
